### ISSUE TITLE
Figure out a nice way to print markdown files.

### ISSUE THREAD

**Issue by zachlatta** [zachlatta/school#7]
I need to figure out a nice way to render and print markdown files (with a header). Make it pretty and automated.

**Comment by simplyluke** [comment]
On the Mac I can recommend [Marked](http://markedapp.com/). Not sure how much you can automate it, but it has some beautiful default renders that I use for school papers.

**Comment by zachlatta** [comment]
Preferably it'd be relatively automated. I'm currently using pandoc to convert the Markdown file to LaTeX and rendering the LaTeX as a PDF for printing. Current issue with this approach is that it's a multi-step process and not all of my teachers are fans of LaTeX default typesetting (no idea what's wrong with them). I'll probably end up writing a script to do the conversion and rendering in one command. I do need to learn how to style LaTeX documents too.

**Comment by simplyluke** [comment]
> Current issue with this approach is that it's a multi-step process and not all of my teachers are fans of LaTeX default typesetting

What? Latex's defaults look clean and professional. I still have teachers that type the majority of their documents in comic sans.

**Comment by zachlatta** [comment]
Yup. Blows my mind. I figure if I use a sans font and use smaller margins it'll "look better".

**Comment by simplyluke** [comment]
@zachlatta You closed the issue. No need for this anymore or did you find a good solution?

**Comment by zachlatta** [comment]
Yeah. Pandoc can convert directly to PDF with `pandoc file.md -o file.pdf`. I've been doing that and then printing the PDF. You can also print directly from vim with `:ha`.
